services:
  postgres:
    image: postgres:16
    container_name: postgres-gestao-ferias
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - ${DB_PORTS}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORTS}

volumes:
  postgres_data:
