server:
  port: ${PORT}

spring:
  application:
    name: api_users

  datasource:
    url: ${DATA_SOUTCE_URL}
    driver-class-name: org.h2.Driver
    username: ${DATA_SOURSE_USERNAME}
    password:

  h2:
    console:
      enabled: ${H2_ENABLED}
      path: ${H2_PATH}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}

  flyway:
    enabled: ${FLYWAY_ENABLE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED}

jwt:
  secret: ${JWT_SECRET:Y2hhbmNlLXRoaXMtaW4tcHJvZHVjdGlvbi1hZGl0ZWMtc2VjcmV0LWtleS0yMDI2LXNwcmluZy1ib290}
  expiration: ${JWT_EXPIRATION:86400000}